name: beszel

services:
  hub:
    container_name: beszel
    image: henrygd/beszel:latest
    ports:
      - ${BESZEL_PORT}:8090
    volumes:
      - ${BESZEL_DATA}:/beszel_data
      - ${BESZEL_SOCKET}:/beszel_socket
    healthcheck:
      test: [CMD, /beszel, health, --url, http://localhost:8090]
      start_period: 5s
      interval: 120s
    labels:
      - dev.dozzle.group=beszel
      - homepage.group=Utilities
      - homepage.name=Beszel
      - homepage.icon=beszel.png
      - homepage.href=http://192.168.50.128:8090/system/MiniServer
      - homepage.description=System Monitoring

  agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest
    network_mode: host
    volumes:
      - ${BESZEL_SOCKET}:/beszel_socket
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${BESZEL_KEY}
    restart:
      unless-stopped
    healthcheck:
      test: [CMD, /agent, health]
      start_period: 5s
      interval: 120s
    labels:
      - dev.dozzle.group=beszel
