services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:latest
    volumes:
      - ./appdata/beszel/data:/beszel_data
      - ./appdata/beszel/socket:/beszel_socket
    ports:
      - 8090:8090

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:latest
    network_mode: host
    volumes:
      - ./appdata/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: 'UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)'
    restart: unless-stopped
