services:
  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:latest
    ports:
      - 8443:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPDATA}/code-server/config:/config
      - ${MINI_SERVER}:/home
    environment:
      PUID: 1000
      PGID: 1000
      PASSWORD: code-server
      HASHED_PASSWORD:
      SUDO_PASSWORD: password
      SUDO_PASSWORD_HASH:
      PROXY_DOMAIN:
      DEFAULT_WORKSPACE: /home
    restart: unless-stopped

  # dozzle:
  #   container_name: dozzle

  # file-browser:
  #   container_name: file-browser

  # glances:
  #   container_name: glances
