services:
  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:latest
    ports:
      - ${CODE_SERVER_PORT}:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPDATA}/code-server:/config
      - ${HOME}:/home
      - ${MINI_SERVER}:/mini-server
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      PASSWORD: code-server
      HASHED_PASSWORD:
      SUDO_PASSWORD: password
      SUDO_PASSWORD_HASH:
      PROXY_DOMAIN:
      DEFAULT_WORKSPACE: /home
    restart: unless-stopped
    labels:
      - homepage.group=Utilities
      - homepage.name=Code Server
      - homepage.icon=code-server.png
      - homepage.href=http://192.168.50.128:8500
      - homepage.description=Visual Studio Code

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - ${DOZZLE_PORT}:8080
    volumes:
      - ${APPDATA}/dozzle:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_REMOTE_AGENT: ${UNRAID_HOSTNAME}:${DOZZLE_AGENT_PORT}
      DOZZLE_HOSTNAME: MiniServer
      DOZZLE_ENABLE_ACTIONS: true
      DOZZLE_ENABLE_SHELL: true
      # DOZZLE_AUTH_PROVIDER: simple # https://dozzle.dev/guide/authentication
    restart: unless-stopped
    healthcheck:
      test: [CMD, /dozzle, healthcheck]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      - homepage.group=Utilities
      - homepage.name=Dozzle
      - homepage.icon=dozzle.png
      - homepage.href=http://192.168.50.128:8080
      - homepage.description=Docker Log Viewer

  file-browser:
    container_name: file-browser
    image: filebrowser/filebrowser:latest
    user: ${PUID}:${PGID}
    ports:
      - ${FILE_BROWSER_PORT}:80
    volumes:
      - ${APPDATA}/file-browser:/config
      - ${HOME}:/home
    environment:
      FB_CONFIG: /config/config.json
      FB_DATABASE: /config/file-browser.db
      FB_ROOT: /home
    restart: unless-stopped
    labels:
      - homepage.group=Utilities
      - homepage.name=File Browser
      - homepage.icon=filebrowser.png
      - homepage.href=http://192.168.50.128:7080/files/mini-server
      - homepage.description=File Manager

  glances:
    container_name: glances
    image: nicolargo/glances:ubuntu-latest-full
    pid: host
    ports:
      - ${GLANCES_PORT}:61208
    volumes:
      - /mnt/user/appdata/glances:/etc/glances
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    environment:
      GLANCES_OPT: -w
    restart: unless-stopped
    labels:
      - homepage.group=Utilities
      - homepage.name=Glances
      - homepage.icon=glances.png
      - homepage.href=http://192.168.50.128:61208
      - homepage.description=Server Monitoring
