name: scrutiny

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - ${SCRUTINY_PORT}:8080
      - ${INFLUXDB_PORT}:8086
    volumes:
      - /run/udev:/run/udev:ro
      - ${SCRUTINY_CONFIG}:/opt/scrutiny/config
      - ${SCRUTINY_INFLUXDB}:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
