name: speedtest-tracker

networks:
  speedtest-tracker:
    name: speedtest-tracker
    driver: bridge

services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    networks:
      - speedtest-tracker
    ports:
      - ${SPEEDTEST_TRACKER_PORT}:80
      - 8443:443
    volumes:
      - ${SPEEDTEST_TRACKER_DATA}/config:/config
      # - /path/to-custom-ssl-keys:/config/keys
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      # App
      APP_NAME: Speedtest Tracker
      APP_KEY: base64:sMZ3vrIEscP6zPNYbCoyweaN9r9UXJkuyRSQJKmL+Oo=
      APP_URL: http://${HOSTNAME}:${SPEEDTEST_TRACKER_PORT}
      APP_TIMEZONE: America/Boise
      DISPLAY_TIMEZONE: America/Boise
      PUBLIC_DASHBOARD: true
      PRUNE_RESULTS_OLDER_THAN: 30
      # Admin user (initial only)
      ADMIN_NAME: Admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password
      # Speedtest
      SPEEDTEST_SCHEDULE: "0 */3 * * *" # Every 3rd hour
      SPEEDTEST_SERVERS: 8182
      # Database
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart:
      unless-stopped
    depends_on:
      - db
    healthcheck:
      test: "curl -fSs APP_URL/api/healthcheck | jq -r .message || exit 1"
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
  
  db:
    container_name: postgres-speedtest-tracker
    image: postgres:17
    networks:
      - speedtest-tracker
    volumes:
      - ${SPEEDTEST_TRACKER_DATA}/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart:
      always
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      retries: 5
      timeout: 5s
  
  # db:
  #   container_name: mariadb-speedtest-tracker
  #   image: mariadb:11
  #   networks:
  #     - speedtest-tracker
  #   volumes:
  #     - ${SPEEDTEST_TRACKER_DATA}/mariadb:/var/lib/mysql
  #   environment:
  #     MARIADB_DATABASE: ${DB_DATABASE}
  #     MARIADB_USER: ${DB_USERNAME}
  #     MARIADB_PASSWORD: ${DB_PASSWORD}
  #     MARIADB_RANDOM_ROOT_PASSWORD: true
  #   restart:
  #     always
  #   healthcheck:
  #     test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
  #     interval: 5s
  #     retries: 3
  #     timeout: 5s
